name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        options:
        - prerelease
        - patch
        - minor
        - major

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version-file: .nvmrc
        registry-url: https://npm.pkg.github.com/
        scope: '@mapquest'
    - name: Run git config
      run: |
        git config user.name GitHub
        git config user.email github-action@users.noreply.github.com
    - run: npm version ${{ github.event.inputs.version }}
    - run: git push origin main --follow-tags
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run npm publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
